const ACL_PERMISSION_DESCRIPTION_KEYS: Readonly<Record<string, string>> = {
  ext_poc_report: "extensionManagement.reportRuntimeDiagnostics",
  ext_data_dir: "extensionManagement.extensionDataDirectory",
  ext_capabilities: "extensionManagement.listAvailableCommands",
  photo_triage_scan: "photoTriage.scanFolder",
  photo_triage_scan_status: "photoTriage.readScanStatus",
  photo_triage_list_recent: "photoTriage.readRecentScans",
  photo_triage_open: "photoTriage.readScanResults",
  photo_triage_capabilities: "photoTriage.readAvailableFeatures",
  photo_triage_ensure_proxy: "photoTriage.createPreviews",
  photo_triage_original_path: "photoTriage.readOriginalFilePath",
  photo_triage_trash: "photoTriage.movePhotosToTrash",
  photo_triage_restore: "photoTriage.restorePhotos",
  photo_triage_move: "photoTriage.movePhotos",
  photo_triage_reveal: "photoTriage.revealPhoto",
  photo_triage_prune: "photoTriage.removeStaleResults",
  photo_triage_empty_dirs: "photoTriage.findEmptyFolders",
  photo_triage_delete_empty_dirs: "photoTriage.deleteEmptyFolders",
  photo_triage_export: "photoTriage.exportPhotos",
  list_terminology_data: "terminology.readLibrary",
  create_industry: "terminology.createIndustry",
  update_industry: "terminology.updateIndustry",
  delete_industry: "terminology.deleteIndustry",
  create_category: "terminology.createCategory",
  update_category: "terminology.updateCategory",
  delete_category: "terminology.deleteCategory",
  create_subcategory: "terminology.createSubcategory",
  update_subcategory: "terminology.updateSubcategory",
  delete_subcategory: "terminology.deleteSubcategory",
  create_term: "terminology.createTerm",
  update_term: "terminology.updateTerm",
  delete_term: "terminology.deleteTerm",
  set_term_pinned: "terminology.setTermPinned",
  scan_storage_overview: "storageCleanup.scanStorage",
  scan_storage_stream: "storageCleanup.readStorageScanProgress",
  get_category_items: "storageCleanup.readCategoryItems",
  execute_category_cleanup: "storageCleanup.deleteSelectedItems",
  scan_custom_folder: "storageCleanup.scanSelectedFolder",
  open_system_storage_settings: "storageCleanup.openSystemStorageSettings",
  get_cleanup_records: "storageCleanup.readCleanupHistory",
  add_cleanup_record: "storageCleanup.recordCleanup",
  scan_dev_projects: "storageCleanup.scanDeveloperProjects",
  cleanup_projects: "storageCleanup.deleteProjectBuildFiles",
  stop_scan: "storageCleanup.stopProjectScan",
  get_custom_cleanup_commands: "storageCleanup.readAvailableCleanupActions",
  execute_custom_cleanup: "storageCleanup.runSelectedCleanupActions",
  stop_custom_cleanup: "storageCleanup.stopCustomCleanup",
  list_pricing_standards: "tokenPricing.readStandards",
  create_pricing_standard: "tokenPricing.createStandard",
  update_pricing_standard: "tokenPricing.updateStandard",
  delete_pricing_standard: "tokenPricing.deleteStandard",
  douyin_assets_get_capabilities: "contentAssets.readAvailableFeatures",
  douyin_assets_list_items: "contentAssets.readAssets",
  douyin_assets_import_files: "contentAssets.importLocalFiles",
  douyin_assets_delete_items: "contentAssets.softDeleteAssets",
  scan_installed_apps: "installedApps.scanInventory",
  cancel_app_inventory_scan: "installedApps.cancelInventoryScan",
  get_cached_app_inventory: "installedApps.readCachedInventory",
  get_app_icon_base64: "installedApps.readAppIcon",
  launch_app: "installedApps.launchApp",
  reveal_app_in_finder: "installedApps.revealApp",
  authorize_mac_app: "installedApps.clearGatekeeperQuarantine",
  check_managed_app_updates: "installedApps.checkSelectedAppUpdates",
  upgrade_app: "installedApps.upgradeApp",
  uninstall_app: "installedApps.uninstallApp",
  batch_upgrade_apps: "installedApps.batchUpgradeApps",
  batch_uninstall_apps: "installedApps.batchUninstallApps",
  install_app: "installedApps.installApp",
  cancel_batch_operation: "installedApps.cancelBatchOperation",
  check_all_app_updates: "installedApps.checkAllAppUpdates",
  open_in_mac_app_store: "installedApps.openAppStoreListing",
  open_in_mac_app_store_updates: "installedApps.openAppStoreUpdates",
  install_app_update: "installedApps.installAppUpdate",
  cancel_app_update: "installedApps.cancelAppUpdate",
}

const DESCRIPTION_PREFIX = "extensionCenter.market.permissionDescriptions."

export function describePermission(command: string, translate: (key: string) => string): string {
  const descriptionKey = Object.prototype.hasOwnProperty.call(
    ACL_PERMISSION_DESCRIPTION_KEYS,
    command,
  )
    ? ACL_PERMISSION_DESCRIPTION_KEYS[command]
    : undefined
  return descriptionKey ? translate(`${DESCRIPTION_PREFIX}${descriptionKey}`) : command
}

export function getPermissionDescriptionKeys(): Readonly<Record<string, string>> {
  return ACL_PERMISSION_DESCRIPTION_KEYS
}
