import {
  createCategory,
  createIndustry,
  createSubcategory,
  createTerm,
  deleteCategory,
  deleteIndustry,
  deleteSubcategory,
  deleteTerm,
  listTerminologyData,
  setTermPinned,
  updateCategory,
  updateIndustry,
  updateSubcategory,
  updateTerm,
} from "@/lib/tauri/commands/terminology";

export {
  createCategory,
  createIndustry,
  createSubcategory,
  createTerm,
  deleteCategory,
  deleteIndustry,
  deleteSubcategory,
  deleteTerm,
  listTerminologyData,
  setTermPinned,
  updateCategory,
  updateIndustry,
  updateSubcategory,
  updateTerm,
};
