use super::types::{Industry, Term, TermCategory, TermSubcategory, TermWebsite};

const UNCLASSIFIED_SUBCATEGORY_ID: &str = "__unclassified__";

fn cat(id: &str, label: &str) -> TermCategory {
    TermCategory {
        id: id.into(),
        label: label.into(),
        subcategories: Vec::new(),
    }
}

fn subcat(id: &str, label: &str) -> TermSubcategory {
    TermSubcategory {
        id: id.into(),
        label: label.into(),
    }
}

fn web(url: &str, label: &str) -> TermWebsite {
    TermWebsite {
        url: url.into(),
        label: Some(label.into()),
    }
}

pub fn builtin_industries() -> Vec<Industry> {
    vec![
        Industry {
            id: "computer".into(),
            label: "计算机".into(),
            categories: vec![
                TermCategory {
                    id: "frontend".into(),
                    label: "前端".into(),
                    subcategories: vec![
                        subcat("framework", "框架"),
                        subcat("styling", "样式"),
                        subcat("design", "设计"),
                        subcat("architecture", "架构"),
                        subcat("engineering", "工程化"),
                        subcat("performance", "性能"),
                        subcat("accessibility", "可访问性"),
                        subcat(UNCLASSIFIED_SUBCATEGORY_ID, "未分类"),
                    ],
                },
                cat("backend", "后端"),
                cat("network", "网络"),
                cat("database", "数据库"),
                cat("devops", "DevOps"),
                cat("security", "安全"),
                cat("architecture", "架构"),
                cat("os", "操作系统"),
                cat("compiler", "编译原理"),
                cat("distributed", "分布式"),
                cat("cloud", "云计算"),
                cat("testing", "测试"),
                cat("algorithm", "算法"),
                cat("mobile", "移动开发"),
            ],
        },
        Industry {
            id: "ai".into(),
            label: "人工智能".into(),
            categories: vec![
                cat("ml", "机器学习"),
                cat("llm", "大语言模型"),
                cat("cv", "计算机视觉"),
                cat("nlp", "自然语言处理"),
                cat("rl", "强化学习"),
            ],
        },
        Industry {
            id: "medicine".into(),
            label: "医疗".into(),
            categories: vec![
                cat("anatomy", "解剖"),
                cat("pharmacology", "药理"),
                cat("diagnosis", "诊断"),
                cat("surgery", "外科"),
                cat("imaging", "影像"),
            ],
        },
        Industry {
            id: "mechanics".into(),
            label: "机械".into(),
            categories: vec![
                cat("kinematics", "运动学"),
                cat("materials", "材料"),
                cat("manufacturing", "制造"),
                cat("hydraulics", "液压"),
                cat("thermodynamics", "热力学"),
            ],
        },
        Industry {
            id: "physics".into(),
            label: "物理".into(),
            categories: vec![
                cat("mechanics_phy", "经典力学"),
                cat("electromagnetism", "电磁学"),
                cat("quantum", "量子力学"),
                cat("thermodynamics_phy", "热力学"),
                cat("optics", "光学"),
            ],
        },
        Industry {
            id: "chemistry".into(),
            label: "化学".into(),
            categories: vec![
                cat("organic", "有机化学"),
                cat("inorganic", "无机化学"),
                cat("physical_chem", "物理化学"),
                cat("analytical", "分析化学"),
                cat("biochem", "生物化学"),
            ],
        },
        Industry {
            id: "biology".into(),
            label: "生物".into(),
            categories: vec![
                cat("cell", "细胞生物"),
                cat("genetics", "遗传学"),
                cat("ecology", "生态学"),
                cat("microbiology", "微生物"),
                cat("botany", "植物学"),
            ],
        },
        Industry {
            id: "finance".into(),
            label: "金融".into(),
            categories: vec![
                cat("investment", "投资"),
                cat("banking", "银行"),
                cat("insurance", "保险"),
                cat("accounting", "会计"),
                cat("derivatives", "衍生品"),
            ],
        },
        Industry {
            id: "law".into(),
            label: "法律".into(),
            categories: vec![
                cat("civil", "民法"),
                cat("criminal", "刑法"),
                cat("commercial", "商法"),
                cat("international", "国际法"),
                cat("ip", "知识产权"),
            ],
        },
        Industry {
            id: "economics".into(),
            label: "经济学".into(),
            categories: vec![
                cat("micro", "微观经济"),
                cat("macro", "宏观经济"),
                cat("international_eco", "国际贸易"),
                cat("behavioral", "行为经济"),
                cat("development", "发展经济"),
            ],
        },
        Industry {
            id: "architecture".into(),
            label: "建筑".into(),
            categories: vec![
                cat("structural", "结构"),
                cat("interior", "室内"),
                cat("urban", "城市规划"),
                cat("construction", "施工"),
                cat("landscape", "景观"),
            ],
        },
        Industry {
            id: "education".into(),
            label: "教育".into(),
            categories: vec![
                cat("pedagogy", "教学法"),
                cat("curriculum", "课程设计"),
                cat("psychology_edu", "教育心理"),
                cat("elearning", "在线教育"),
            ],
        },
        Industry {
            id: "psychology".into(),
            label: "心理学".into(),
            categories: vec![
                cat("clinical", "临床心理"),
                cat("cognitive", "认知心理"),
                cat("social_psy", "社会心理"),
                cat("developmental", "发展心理"),
                cat("abnormal", "异常心理"),
            ],
        },
        Industry {
            id: "marketing".into(),
            label: "市场营销".into(),
            categories: vec![
                cat("branding", "品牌"),
                cat("digital_mkt", "数字营销"),
                cat("consumer", "消费者行为"),
                cat("seo", "SEO/SEM"),
                cat("crm", "客户关系"),
            ],
        },
        Industry {
            id: "management".into(),
            label: "管理学".into(),
            categories: vec![
                cat("hr", "人力资源"),
                cat("strategy", "战略管理"),
                cat("operations", "运营管理"),
                cat("project", "项目管理"),
                cat("supply_chain", "供应链"),
            ],
        },
        Industry {
            id: "electric".into(),
            label: "电气".into(),
            categories: vec![
                cat("power", "电力系统"),
                cat("control", "控制系统"),
                cat("electronics", "电子"),
                cat("embedded", "嵌入式"),
                cat("signal", "信号处理"),
            ],
        },
        Industry {
            id: "energy".into(),
            label: "能源".into(),
            categories: vec![
                cat("renewable", "可再生能源"),
                cat("oil_gas", "石油天然气"),
                cat("nuclear", "核能"),
                cat("storage", "储能"),
                cat("grid", "电网"),
            ],
        },
        Industry {
            id: "environment".into(),
            label: "环境".into(),
            categories: vec![
                cat("pollution", "污染治理"),
                cat("ecology_env", "生态保护"),
                cat("climate", "气候变化"),
                cat("water", "水资源"),
                cat("waste", "废物处理"),
            ],
        },
        Industry {
            id: "food".into(),
            label: "食品".into(),
            categories: vec![
                cat("nutrition", "营养学"),
                cat("processing", "食品加工"),
                cat("safety", "食品安全"),
                cat("fermentation", "发酵"),
            ],
        },
        Industry {
            id: "agriculture".into(),
            label: "农业".into(),
            categories: vec![
                cat("planting", "种植业"),
                cat("livestock", "畜牧业"),
                cat("agritech", "农业科技"),
                cat("soil", "土壤科学"),
            ],
        },
        Industry {
            id: "transportation".into(),
            label: "交通运输".into(),
            categories: vec![
                cat("aviation", "航空"),
                cat("shipping", "航运"),
                cat("railway", "铁路"),
                cat("road", "公路"),
                cat("logistics", "物流"),
            ],
        },
        Industry {
            id: "materials".into(),
            label: "材料科学".into(),
            categories: vec![
                cat("metals", "金属材料"),
                cat("polymer", "高分子"),
                cat("composite", "复合材料"),
                cat("semiconductor", "半导体"),
                cat("nanomaterials", "纳米材料"),
            ],
        },
        Industry {
            id: "aerospace".into(),
            label: "航空航天".into(),
            categories: vec![
                cat("propulsion", "推进系统"),
                cat("astrodynamics", "轨道力学"),
                cat("avionics", "航电"),
                cat("structures", "结构"),
            ],
        },
        Industry {
            id: "philosophy".into(),
            label: "哲学".into(),
            categories: vec![
                cat("metaphysics", "形而上学"),
                cat("epistemology", "认识论"),
                cat("ethics", "伦理学"),
                cat("logic", "逻辑学"),
            ],
        },
        Industry {
            id: "sociology".into(),
            label: "社会学".into(),
            categories: vec![
                cat("social_structure", "社会结构"),
                cat("culture", "文化研究"),
                cat("demography", "人口学"),
                cat("criminology", "犯罪学"),
            ],
        },
        Industry {
            id: "media".into(),
            label: "传媒".into(),
            categories: vec![
                cat("journalism", "新闻"),
                cat("broadcasting", "广播电视"),
                cat("social_media", "社交媒体"),
                cat("pr", "公关"),
            ],
        },
        Industry {
            id: "art_design".into(),
            label: "艺术与设计".into(),
            categories: vec![
                cat("graphic", "平面设计"),
                cat("ux_ui", "UX/UI"),
                cat("film", "影视"),
                cat("music", "音乐"),
                cat("industrial_design", "工业设计"),
            ],
        },
        Industry {
            id: "statistics".into(),
            label: "统计学".into(),
            categories: vec![
                cat("probability", "概率论"),
                cat("inference", "推断统计"),
                cat("regression", "回归分析"),
                cat("bayesian", "贝叶斯统计"),
            ],
        },
        Industry {
            id: "mathematics".into(),
            label: "数学".into(),
            categories: vec![
                cat("algebra", "代数"),
                cat("calculus", "微积分"),
                cat("geometry", "几何"),
                cat("number_theory", "数论"),
                cat("topology", "拓扑学"),
            ],
        },
        Industry {
            id: "real_estate".into(),
            label: "房地产".into(),
            categories: vec![
                cat("valuation", "估价"),
                cat("development", "开发"),
                cat("property_mgt", "物业管理"),
                cat("financing", "融资"),
            ],
        },
    ]
}

pub fn builtin_terms() -> Vec<Term> {
    vec![
        // 计算机 · 前端
        Term {
            id: "t-1".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("architecture".into()),
            title: "虚拟 DOM / Virtual DOM".into(),
            description: "浏览器真实 DOM 的轻量 JavaScript 对象映射，通过 diff 算法批量更新，减少重绘重排开销。".into(),
            websites: vec![
                web("https://react.dev/learn/preserving-and-resetting-state", "React 文档"),
                web("https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model", "MDN DOM"),
            ],
        },
        Term {
            id: "t-2".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("engineering".into()),
            title: "摇树优化 / Tree Shaking".into(),
            description: "静态分析模块导入/导出，删除未被引用的代码，减小打包产物体积的优化手段。".into(),
            websites: vec![web("https://webpack.js.org/guides/tree-shaking/", "Webpack 文档")],
        },
        Term {
            id: "t-3".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("performance".into()),
            title: "CSS 包含 / CSS Containment".into(),
            description: "通过 contain 属性将元素渲染隔离到子树，提升渲染性能。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment", "MDN")],
        },
        Term {
            id: "t-26".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("architecture".into()),
            title: "水合 / Hydration".into(),
            description: "服务端渲染后的静态 HTML 由前端运行时接管并绑定事件的过程。".into(),
            websites: vec![web("https://react.dev/reference/react-dom/client/hydrateRoot", "React hydrateRoot")],
        },
        Term {
            id: "t-27".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("engineering".into()),
            title: "代码分割 / Code Splitting".into(),
            description: "将应用拆分为多个按需加载的代码块，降低首屏加载成本。".into(),
            websites: vec![web("https://webpack.js.org/guides/code-splitting/", "Webpack 文档")],
        },
        Term {
            id: "t-28".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("architecture".into()),
            title: "服务工作线程 / Service Worker".into(),
            description: "运行在浏览器后台的脚本，可用于离线缓存、消息推送和网络代理能力。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API", "MDN")],
        },
        Term {
            id: "t-88".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "侧边栏 / Sidebar".into(),
            description: "位于页面左侧或右侧的辅助栏，通常承载导航、筛选、目录或工具操作。".into(),
            websites: vec![],
        },
        Term {
            id: "t-89".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "顶部栏 / Header".into(),
            description: "页面顶部区域，通常包含标题、全局导航、搜索和主要操作入口。".into(),
            websites: vec![],
        },
        Term {
            id: "t-90".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "底部栏 / Footer".into(),
            description: "页面底部区域，常用于放置补充导航、版权信息和次级操作。".into(),
            websites: vec![],
        },
        Term {
            id: "t-91".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "主内容区 / Main Content".into(),
            description: "页面主要内容区，是用户当前任务最核心的信息承载区域。".into(),
            websites: vec![],
        },
        Term {
            id: "t-92".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "三栏布局 / Three-column Layout".into(),
            description: "三栏布局，通常由导航栏、主内容区和详情栏或工具栏组成。".into(),
            websites: vec![],
        },
        Term {
            id: "t-93".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "双栏布局 / Two-column Layout".into(),
            description: "双栏布局，常用于列表加详情、内容区加侧栏等界面结构。".into(),
            websites: vec![],
        },
        Term {
            id: "t-94".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "上下布局 / Vertical Layout".into(),
            description: "上下布局，内容按照垂直方向依次堆叠排列。".into(),
            websites: vec![],
        },
        Term {
            id: "t-95".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("styling".into()),
            title: "栅格布局 / Grid Layout".into(),
            description: "栅格布局，通过行列网格组织模块，适合卡片、图库和仪表盘。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout", "MDN")],
        },
        Term {
            id: "t-96".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("styling".into()),
            title: "弹性布局 / Flex Layout".into(),
            description: "弹性布局，常用于一维方向上的对齐、分布和伸缩控制。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout", "MDN")],
        },
        Term {
            id: "t-97".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "响应式设计 / Responsive Design".into(),
            description: "响应式设计，使界面能够根据屏幕尺寸和设备特性自动调整布局与样式。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design", "MDN")],
        },
        Term {
            id: "t-98".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "断点 / Breakpoint".into(),
            description: "断点，响应式布局中用于切换样式规则的屏幕宽度或条件阈值。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries", "MDN")],
        },
        Term {
            id: "t-99".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "容器 / Container".into(),
            description: "容器，用于包裹内容并统一控制宽度、边距、对齐和内部布局。".into(),
            websites: vec![],
        },
        Term {
            id: "t-100".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "留白 / Whitespace".into(),
            description: "留白，利用空白区域分隔信息层级，提升可读性和界面节奏。".into(),
            websites: vec![],
        },
        Term {
            id: "t-101".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "标签页 / Tabs".into(),
            description: "标签页，通过切换页签在同一内容区域内展示不同面板。".into(),
            websites: vec![],
        },
        Term {
            id: "t-102".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "抽屉 / Drawer".into(),
            description: "抽屉面板，从屏幕边缘滑入的临时内容区，常用于表单和详情编辑。".into(),
            websites: vec![],
        },
        Term {
            id: "t-103".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "模态框 / Modal".into(),
            description: "模态框，打开后会阻断当前页面上下文，要求用户先完成当前交互。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/dialog_role", "MDN")],
        },
        Term {
            id: "t-104".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "悬浮层 / Popover".into(),
            description: "悬浮层，依附于某个触发元素显示附加信息或轻量操作。".into(),
            websites: vec![],
        },
        Term {
            id: "t-105".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("design".into()),
            title: "工具提示 / Tooltip".into(),
            description: "工具提示，在悬停或聚焦时显示元素说明、状态解释或辅助信息。".into(),
            websites: vec![],
        },
        Term {
            id: "t-106".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("framework".into()),
            title: "钩子 / Hooks".into(),
            description: "React 中复用状态、生命周期和副作用逻辑的一组函数式机制。".into(),
            websites: vec![web("https://react.dev/reference/react", "React 文档")],
        },
        Term {
            id: "t-107".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("architecture".into()),
            title: "状态管理 / State Management".into(),
            description: "状态管理，负责维护组件内或应用级数据状态及其更新流转。".into(),
            websites: vec![],
        },
        Term {
            id: "t-108".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("architecture".into()),
            title: "路由 / Routing".into(),
            description: "路由，将 URL、页面状态和视图组件之间建立映射关系。".into(),
            websites: vec![],
        },
        Term {
            id: "t-109".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("engineering".into()),
            title: "国际化 / Internationalization (i18n)".into(),
            description: "国际化，为多语言、多地区格式和跨文化内容适配预留统一能力。".into(),
            websites: vec![],
        },
        Term {
            id: "t-110".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("engineering".into()),
            title: "本地化 / Localization (l10n)".into(),
            description: "本地化，针对具体语言和地区落地翻译、日期、数字、货币等展示规则。".into(),
            websites: vec![],
        },
        Term {
            id: "t-111".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("styling".into()),
            title: "主题系统 / Theming".into(),
            description: "主题系统，用于统一控制颜色、字体、圆角、阴影和明暗模式切换。".into(),
            websites: vec![],
        },
        Term {
            id: "t-112".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("accessibility".into()),
            title: "可访问性 / Accessibility (a11y)".into(),
            description: "可访问性，确保键盘用户、读屏用户和其他辅助技术用户都能正常使用界面。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Learn/Accessibility", "MDN")],
        },
        Term {
            id: "t-113".into(),
            industry_id: "computer".into(),
            category_id: "frontend".into(),
            subcategory_id: Some("accessibility".into()),
            title: "语义化 HTML / Semantic HTML".into(),
            description: "语义化 HTML，使用具有明确结构意义的标签提升可访问性和可维护性。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Glossary/Semantics", "MDN")],
        },

        // 计算机 · 后端
        Term {
            id: "t-4".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "gRPC".into(),
            description: "Google 开源的高性能 RPC 框架，基于 HTTP/2 和 Protocol Buffers，支持双向流。".into(),
            websites: vec![web("https://grpc.io/", "官网")],
        },
        Term {
            id: "t-5".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "CQRS".into(),
            description: "命令查询职责分离模式，将写操作（命令）和读操作（查询）分离为不同模型，便于独立扩展。".into(),
            websites: vec![web("https://martinfowler.com/bliki/CQRS.html", "Martin Fowler")],
        },
        Term {
            id: "t-6".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "Event Sourcing".into(),
            description: "将状态变更持久化为不可变事件序列，可重放事件以恢复任意时刻的系统状态。".into(),
            websites: vec![web("https://martinfowler.com/eaaDev/EventSourcing.html", "Martin Fowler")],
        },
        Term {
            id: "t-29".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "REST".into(),
            description: "面向资源的 HTTP API 风格，强调统一接口、无状态和可缓存。".into(),
            websites: vec![web("https://www.ics.uci.edu/~fielding/pubs/dissertation/rest_arch_style.htm", "Roy Fielding")],
        },
        Term {
            id: "t-30".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "Idempotency".into(),
            description: "重复执行相同请求仍得到相同结果的性质，是支付、回调和重试设计的关键。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Glossary/Idempotent", "MDN")],
        },
        Term {
            id: "t-31".into(),
            industry_id: "computer".into(),
            category_id: "backend".into(),
            subcategory_id: None,
            title: "Circuit Breaker".into(),
            description: "在调用失败率过高时快速熔断，防止故障在分布式系统中级联扩散。".into(),
            websites: vec![web("https://martinfowler.com/bliki/CircuitBreaker.html", "Martin Fowler")],
        },

        // 计算机 · 网络
        Term {
            id: "t-7".into(),
            industry_id: "computer".into(),
            category_id: "network".into(),
            subcategory_id: None,
            title: "BGP".into(),
            description: "边界网关协议，互联网核心路由协议，负责在自治系统之间交换路由信息。".into(),
            websites: vec![web("https://datatracker.ietf.org/doc/html/rfc4271", "RFC 4271")],
        },
        Term {
            id: "t-8".into(),
            industry_id: "computer".into(),
            category_id: "network".into(),
            subcategory_id: None,
            title: "QUIC".into(),
            description: "基于 UDP 的多路复用传输协议，HTTP/3 的底层，解决 TCP 队头阻塞问题。".into(),
            websites: vec![web("https://quicwg.org/", "QUIC WG")],
        },
        Term {
            id: "t-32".into(),
            industry_id: "computer".into(),
            category_id: "network".into(),
            subcategory_id: None,
            title: "CDN".into(),
            description: "通过分布式边缘节点缓存和分发内容，降低延迟并提升吞吐。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Glossary/CDN", "MDN")],
        },
        Term {
            id: "t-33".into(),
            industry_id: "computer".into(),
            category_id: "network".into(),
            subcategory_id: None,
            title: "TLS".into(),
            description: "传输层安全协议，为通信提供加密、完整性和身份验证。".into(),
            websites: vec![web("https://datatracker.ietf.org/doc/html/rfc8446", "RFC 8446")],
        },
        Term {
            id: "t-34".into(),
            industry_id: "computer".into(),
            category_id: "network".into(),
            subcategory_id: None,
            title: "HTTP/2".into(),
            description: "支持多路复用、头部压缩和服务器推送的 HTTP 版本。".into(),
            websites: vec![web("https://httpwg.org/specs/rfc7540.html", "RFC 7540")],
        },

        // 计算机 · 数据库
        Term {
            id: "t-9".into(),
            industry_id: "computer".into(),
            category_id: "database".into(),
            subcategory_id: None,
            title: "MVCC".into(),
            description: "多版本并发控制，通过保存数据快照实现读写不互锁，PostgreSQL、MySQL InnoDB 均采用此方式。".into(),
            websites: vec![web("https://www.postgresql.org/docs/current/mvcc.html", "PostgreSQL 文档")],
        },
        Term {
            id: "t-10".into(),
            industry_id: "computer".into(),
            category_id: "database".into(),
            subcategory_id: None,
            title: "LSM Tree".into(),
            description: "日志结构合并树，写优化数据结构，广泛用于 RocksDB、LevelDB、Cassandra。".into(),
            websites: vec![web("https://rocksdb.org/blog/2021/05/26/rocksdb-lsm.html", "RocksDB 博客")],
        },
        Term {
            id: "t-35".into(),
            industry_id: "computer".into(),
            category_id: "database".into(),
            subcategory_id: None,
            title: "ACID".into(),
            description: "原子性、一致性、隔离性、持久性的事务特征集合。".into(),
            websites: vec![web("https://www.postgresql.org/docs/current/tutorial-transactions.html", "PostgreSQL 事务")],
        },
        Term {
            id: "t-36".into(),
            industry_id: "computer".into(),
            category_id: "database".into(),
            subcategory_id: None,
            title: "Index".into(),
            description: "用于加速查询的数据结构，通常以额外存储换取更快检索。".into(),
            websites: vec![web("https://use-the-index-luke.com/", "Use the Index, Luke")],
        },
        Term {
            id: "t-37".into(),
            industry_id: "computer".into(),
            category_id: "database".into(),
            subcategory_id: None,
            title: "Sharding".into(),
            description: "将数据按某种规则拆分到多个分片，以扩展存储和读写吞吐。".into(),
            websites: vec![web("https://www.mongodb.com/resources/basics/databases/sharding", "MongoDB")],
        },

        // 计算机 · DevOps
        Term {
            id: "t-38".into(),
            industry_id: "computer".into(),
            category_id: "devops".into(),
            subcategory_id: None,
            title: "CI/CD".into(),
            description: "持续集成与持续交付/部署，通过流水线自动化测试、构建和发布。".into(),
            websites: vec![web("https://www.redhat.com/en/topics/devops/what-is-ci-cd", "Red Hat")],
        },
        Term {
            id: "t-39".into(),
            industry_id: "computer".into(),
            category_id: "devops".into(),
            subcategory_id: None,
            title: "Infrastructure as Code".into(),
            description: "用代码和配置声明式管理基础设施，提升一致性和可回滚性。".into(),
            websites: vec![web("https://www.terraform.io/intro", "Terraform")],
        },
        Term {
            id: "t-40".into(),
            industry_id: "computer".into(),
            category_id: "devops".into(),
            subcategory_id: None,
            title: "Observability".into(),
            description: "通过日志、指标和链路追踪推断系统内部状态的能力。".into(),
            websites: vec![web("https://www.cncf.io/blog/2022/02/07/what-is-observability/", "CNCF")],
        },
        Term {
            id: "t-41".into(),
            industry_id: "computer".into(),
            category_id: "devops".into(),
            subcategory_id: None,
            title: "Canary Release".into(),
            description: "先将新版本发布给少量用户，验证稳定后再逐步全量放开。".into(),
            websites: vec![web("https://martinfowler.com/bliki/CanaryRelease.html", "Martin Fowler")],
        },
        Term {
            id: "t-42".into(),
            industry_id: "computer".into(),
            category_id: "devops".into(),
            subcategory_id: None,
            title: "Blue-Green Deployment".into(),
            description: "同时维护两个生产环境，通过流量切换完成无缝发布和快速回滚。".into(),
            websites: vec![web("https://learn.microsoft.com/en-us/azure/architecture/patterns/blue-green-deployment", "Microsoft")],
        },

        // 计算机 · 安全
        Term {
            id: "t-43".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "Authentication".into(),
            description: "验证用户或系统身份的过程，回答“你是谁”。".into(),
            websites: vec![web("https://developer.okta.com/blog/2019/10/21/what-is-authentication", "Okta")],
        },
        Term {
            id: "t-44".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "Authorization".into(),
            description: "根据身份和策略授予资源访问权限的过程，回答“你能做什么”。".into(),
            websites: vec![web("https://www.cloudflare.com/learning/access-management/authorization/", "Cloudflare")],
        },
        Term {
            id: "t-45".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "OAuth 2.0".into(),
            description: "授权框架，允许第三方应用在用户授权下访问受保护资源。".into(),
            websites: vec![web("https://oauth.net/2/", "OAuth 2.0")],
        },
        Term {
            id: "t-46".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "Zero Trust".into(),
            description: "默认不信任任何网络位置或主体，持续验证身份、设备和上下文。".into(),
            websites: vec![web("https://www.cisa.gov/zero-trust-maturity-model", "CISA")],
        },
        Term {
            id: "t-47".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "XSS".into(),
            description: "跨站脚本攻击，攻击者借助网页注入恶意脚本劫持用户会话。".into(),
            websites: vec![web("https://owasp.org/www-community/attacks/xss/", "OWASP")],
        },
        Term {
            id: "t-48".into(),
            industry_id: "computer".into(),
            category_id: "security".into(),
            subcategory_id: None,
            title: "SQL Injection".into(),
            description: "通过构造恶意 SQL 片段操纵数据库执行逻辑的攻击方式。".into(),
            websites: vec![web("https://owasp.org/www-community/attacks/SQL_Injection", "OWASP")],
        },

        // 计算机 · 架构
        Term {
            id: "t-49".into(),
            industry_id: "computer".into(),
            category_id: "architecture".into(),
            subcategory_id: None,
            title: "Monolith".into(),
            description: "单体架构将主要业务逻辑部署在一个进程或一个应用中。".into(),
            websites: vec![web("https://martinfowler.com/bliki/MonolithFirst.html", "Martin Fowler")],
        },
        Term {
            id: "t-50".into(),
            industry_id: "computer".into(),
            category_id: "architecture".into(),
            subcategory_id: None,
            title: "Microservices".into(),
            description: "把系统拆分为多个围绕业务能力的小型独立服务。".into(),
            websites: vec![web("https://microservices.io/", "Microservices.io")],
        },
        Term {
            id: "t-51".into(),
            industry_id: "computer".into(),
            category_id: "architecture".into(),
            subcategory_id: None,
            title: "Hexagonal Architecture".into(),
            description: "通过端口和适配器隔离领域模型与外部技术细节。".into(),
            websites: vec![web("https://alistair.cockburn.us/hexagonal-architecture/", "Alistair Cockburn")],
        },
        Term {
            id: "t-52".into(),
            industry_id: "computer".into(),
            category_id: "architecture".into(),
            subcategory_id: None,
            title: "DDD".into(),
            description: "领域驱动设计，围绕业务领域建模和划分限界上下文。".into(),
            websites: vec![web("https://martinfowler.com/tags/domain%20driven%20design.html", "Martin Fowler")],
        },
        Term {
            id: "t-53".into(),
            industry_id: "computer".into(),
            category_id: "architecture".into(),
            subcategory_id: None,
            title: "Bounded Context".into(),
            description: "在 DDD 中为某一模型和语言定义明确边界的语义范围。".into(),
            websites: vec![web("https://martinfowler.com/bliki/BoundedContext.html", "Martin Fowler")],
        },

        // 计算机 · 操作系统
        Term {
            id: "t-54".into(),
            industry_id: "computer".into(),
            category_id: "os".into(),
            subcategory_id: None,
            title: "Process".into(),
            description: "正在执行中的程序实例，拥有独立地址空间和资源。".into(),
            websites: vec![web("https://www.geeksforgeeks.org/process-vs-thread/", "GFG")],
        },
        Term {
            id: "t-55".into(),
            industry_id: "computer".into(),
            category_id: "os".into(),
            subcategory_id: None,
            title: "Thread".into(),
            description: "进程内的执行单元，线程之间共享进程资源。".into(),
            websites: vec![web("https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API", "MDN")],
        },
        Term {
            id: "t-56".into(),
            industry_id: "computer".into(),
            category_id: "os".into(),
            subcategory_id: None,
            title: "Virtual Memory".into(),
            description: "为进程提供抽象统一的地址空间，背后由分页和映射机制支持。".into(),
            websites: vec![web("https://www.cs.virginia.edu/~evans/cs4414/readings/paging.pdf", "Paging")],
        },
        Term {
            id: "t-57".into(),
            industry_id: "computer".into(),
            category_id: "os".into(),
            subcategory_id: None,
            title: "Context Switch".into(),
            description: "CPU 在不同进程或线程之间切换时保存和恢复执行上下文的过程。".into(),
            websites: vec![web("https://www.sciencedirect.com/topics/computer-science/context-switch", "ScienceDirect")],
        },
        Term {
            id: "t-58".into(),
            industry_id: "computer".into(),
            category_id: "os".into(),
            subcategory_id: None,
            title: "Deadlock".into(),
            description: "多个进程互相等待对方持有的资源，导致系统永久阻塞。".into(),
            websites: vec![web("https://docs.oracle.com/javase/tutorial/essential/concurrency/deadlock.html", "Oracle")],
        },

        // 计算机 · 编译原理
        Term {
            id: "t-59".into(),
            industry_id: "computer".into(),
            category_id: "compiler".into(),
            subcategory_id: None,
            title: "Lexer".into(),
            description: "将源代码字符串切分为词法单元的阶段。".into(),
            websites: vec![web("https://craftinginterpreters.com/scanning.html", "Crafting Interpreters")],
        },
        Term {
            id: "t-60".into(),
            industry_id: "computer".into(),
            category_id: "compiler".into(),
            subcategory_id: None,
            title: "Parser".into(),
            description: "根据语法规则将词法单元构建为语法树的阶段。".into(),
            websites: vec![web("https://craftinginterpreters.com/parsing-expressions.html", "Crafting Interpreters")],
        },
        Term {
            id: "t-61".into(),
            industry_id: "computer".into(),
            category_id: "compiler".into(),
            subcategory_id: None,
            title: "AST".into(),
            description: "抽象语法树，是源代码结构的层级化表示。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Abstract_syntax_tree", "Wikipedia")],
        },
        Term {
            id: "t-62".into(),
            industry_id: "computer".into(),
            category_id: "compiler".into(),
            subcategory_id: None,
            title: "SSA".into(),
            description: "静态单赋值形式，每个变量只被赋值一次，便于优化。".into(),
            websites: vec![web("https://www.cs.cornell.edu/courses/cs6120/2019fa/blog/ssa/", "Cornell")],
        },
        Term {
            id: "t-63".into(),
            industry_id: "computer".into(),
            category_id: "compiler".into(),
            subcategory_id: None,
            title: "JIT".into(),
            description: "运行时即时编译，在执行阶段动态生成优化后的机器码。".into(),
            websites: vec![web("https://www.ibm.com/docs/en/sdk-java-technology/8?topic=technology-just-in-time-jit-compiler", "IBM")],
        },

        // 计算机 · 分布式
        Term {
            id: "t-64".into(),
            industry_id: "computer".into(),
            category_id: "distributed".into(),
            subcategory_id: None,
            title: "CAP".into(),
            description: "一致性、可用性、分区容错性，分布式系统只能同时满足其中两项。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/CAP_theorem", "Wikipedia")],
        },
        Term {
            id: "t-65".into(),
            industry_id: "computer".into(),
            category_id: "distributed".into(),
            subcategory_id: None,
            title: "Raft".into(),
            description: "用于复制日志和达成一致的共识算法，设计上更易理解。".into(),
            websites: vec![web("https://raft.github.io/", "Raft")],
        },
        Term {
            id: "t-66".into(),
            industry_id: "computer".into(),
            category_id: "distributed".into(),
            subcategory_id: None,
            title: "Paxos".into(),
            description: "经典共识算法家族，解决分布式系统中一致性达成问题。".into(),
            websites: vec![web("https://lamport.azurewebsites.net/pubs/paxos-simple.pdf", "Paxos 论文")],
        },
        Term {
            id: "t-67".into(),
            industry_id: "computer".into(),
            category_id: "distributed".into(),
            subcategory_id: None,
            title: "Eventual Consistency".into(),
            description: "在没有新更新的前提下，副本最终会收敛到相同状态的一致性模型。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Eventual_consistency", "Wikipedia")],
        },
        Term {
            id: "t-68".into(),
            industry_id: "computer".into(),
            category_id: "distributed".into(),
            subcategory_id: None,
            title: "Distributed Lock".into(),
            description: "跨多个节点协调对共享资源互斥访问的机制。".into(),
            websites: vec![web("https://redis.io/docs/latest/develop/use/patterns/distributed-locks/", "Redis")],
        },

        // 计算机 · 云计算
        Term {
            id: "t-69".into(),
            industry_id: "computer".into(),
            category_id: "cloud".into(),
            subcategory_id: None,
            title: "Kubernetes".into(),
            description: "用于容器编排的开源系统，负责部署、调度和自愈。".into(),
            websites: vec![web("https://kubernetes.io/", "Kubernetes")],
        },
        Term {
            id: "t-70".into(),
            industry_id: "computer".into(),
            category_id: "cloud".into(),
            subcategory_id: None,
            title: "Serverless".into(),
            description: "把基础设施管理抽象掉，由平台按调用量自动伸缩计费。".into(),
            websites: vec![web("https://aws.amazon.com/serverless/", "AWS Serverless")],
        },
        Term {
            id: "t-71".into(),
            industry_id: "computer".into(),
            category_id: "cloud".into(),
            subcategory_id: None,
            title: "Autoscaling".into(),
            description: "根据负载自动增加或减少实例数量的机制。".into(),
            websites: vec![web("https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/", "HPA")],
        },
        Term {
            id: "t-72".into(),
            industry_id: "computer".into(),
            category_id: "cloud".into(),
            subcategory_id: None,
            title: "Load Balancer".into(),
            description: "在多个后端实例之间分发流量，提升可用性和吞吐。".into(),
            websites: vec![web("https://www.nginx.com/resources/glossary/load-balancing/", "NGINX")],
        },
        Term {
            id: "t-73".into(),
            industry_id: "computer".into(),
            category_id: "cloud".into(),
            subcategory_id: None,
            title: "Object Storage".into(),
            description: "以对象为单位存储数据的云存储模型，适合海量非结构化文件。".into(),
            websites: vec![web("https://aws.amazon.com/s3/", "Amazon S3")],
        },

        // 计算机 · 测试
        Term {
            id: "t-74".into(),
            industry_id: "computer".into(),
            category_id: "testing".into(),
            subcategory_id: None,
            title: "Unit Test".into(),
            description: "验证单个函数或模块行为的自动化测试。".into(),
            websites: vec![web("https://martinfowler.com/bliki/UnitTest.html", "Martin Fowler")],
        },
        Term {
            id: "t-75".into(),
            industry_id: "computer".into(),
            category_id: "testing".into(),
            subcategory_id: None,
            title: "Integration Test".into(),
            description: "验证多个组件协同工作的测试。".into(),
            websites: vec![web("https://martinfowler.com/bliki/IntegrationTest.html", "Martin Fowler")],
        },
        Term {
            id: "t-76".into(),
            industry_id: "computer".into(),
            category_id: "testing".into(),
            subcategory_id: None,
            title: "E2E".into(),
            description: "端到端测试，从用户视角验证完整业务流程。".into(),
            websites: vec![web("https://www.cypress.io/how-it-works/", "Cypress")],
        },
        Term {
            id: "t-77".into(),
            industry_id: "computer".into(),
            category_id: "testing".into(),
            subcategory_id: None,
            title: "Mock".into(),
            description: "用可控替身替代外部依赖，隔离测试目标。".into(),
            websites: vec![web("https://docs.rs/mockall/latest/mockall/", "Mockall")],
        },
        Term {
            id: "t-78".into(),
            industry_id: "computer".into(),
            category_id: "testing".into(),
            subcategory_id: None,
            title: "Fuzzing".into(),
            description: "通过大量半随机输入发现崩溃、越界和逻辑漏洞的测试技术。".into(),
            websites: vec![web("https://llvm.org/docs/LibFuzzer.html", "LibFuzzer")],
        },

        // 计算机 · 算法
        Term {
            id: "t-79".into(),
            industry_id: "computer".into(),
            category_id: "algorithm".into(),
            subcategory_id: None,
            title: "Big-O".into(),
            description: "描述算法时间或空间复杂度增长上界的记号。".into(),
            websites: vec![web("https://www.bigocheatsheet.com/", "Big-O Cheat Sheet")],
        },
        Term {
            id: "t-80".into(),
            industry_id: "computer".into(),
            category_id: "algorithm".into(),
            subcategory_id: None,
            title: "Dynamic Programming".into(),
            description: "将原问题拆为重叠子问题并缓存结果的求解方法。".into(),
            websites: vec![web("https://cp-algorithms.com/dynamic_programming/intro-to-dp.html", "CP Algorithms")],
        },
        Term {
            id: "t-81".into(),
            industry_id: "computer".into(),
            category_id: "algorithm".into(),
            subcategory_id: None,
            title: "Greedy".into(),
            description: "每一步都选择局部最优解的算法范式。".into(),
            websites: vec![web("https://cp-algorithms.com/greedy/", "CP Algorithms")],
        },
        Term {
            id: "t-82".into(),
            industry_id: "computer".into(),
            category_id: "algorithm".into(),
            subcategory_id: None,
            title: "Dijkstra".into(),
            description: "用于求单源最短路径的经典图算法。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm", "Wikipedia")],
        },
        Term {
            id: "t-83".into(),
            industry_id: "computer".into(),
            category_id: "algorithm".into(),
            subcategory_id: None,
            title: "Binary Search".into(),
            description: "在有序集合上通过折半缩小搜索区间的查找算法。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Binary_search_algorithm", "Wikipedia")],
        },

        // 计算机 · 移动开发
        Term {
            id: "t-84".into(),
            industry_id: "computer".into(),
            category_id: "mobile".into(),
            subcategory_id: None,
            title: "Activity".into(),
            description: "Android 中承载一个用户界面的基础组件。".into(),
            websites: vec![web("https://developer.android.com/guide/components/activities/intro-activities", "Android")],
        },
        Term {
            id: "t-85".into(),
            industry_id: "computer".into(),
            category_id: "mobile".into(),
            subcategory_id: None,
            title: "ViewController".into(),
            description: "iOS 中管理视图层次与交互逻辑的核心控制器。".into(),
            websites: vec![web("https://developer.apple.com/documentation/uikit/uiviewcontroller", "Apple")],
        },
        Term {
            id: "t-86".into(),
            industry_id: "computer".into(),
            category_id: "mobile".into(),
            subcategory_id: None,
            title: "React Native Bridge".into(),
            description: "React Native 中 JavaScript 与原生模块通信的桥接层。".into(),
            websites: vec![web("https://reactnative.dev/docs/bridging", "React Native")],
        },
        Term {
            id: "t-87".into(),
            industry_id: "computer".into(),
            category_id: "mobile".into(),
            subcategory_id: None,
            title: "Flutter Widget".into(),
            description: "Flutter 的 UI 构建单元，界面由 Widget 树组合而成。".into(),
            websites: vec![web("https://docs.flutter.dev/ui/widgets", "Flutter")],
        },

        // AI · 大语言模型
        Term {
            id: "t-11".into(),
            industry_id: "ai".into(),
            category_id: "llm".into(),
            subcategory_id: None,
            title: "Transformer".into(),
            description: "基于自注意力机制的神经网络架构，是 GPT、BERT 等现代大语言模型的基础。".into(),
            websites: vec![
                web("https://arxiv.org/abs/1706.03762", "原始论文"),
                web("https://huggingface.co/docs/transformers/index", "HuggingFace"),
            ],
        },
        Term {
            id: "t-12".into(),
            industry_id: "ai".into(),
            category_id: "llm".into(),
            subcategory_id: None,
            title: "RAG".into(),
            description: "检索增强生成，将外部知识库检索结果与 LLM 生成结合，减少幻觉、提升知识时效性。".into(),
            websites: vec![web("https://arxiv.org/abs/2005.11401", "原始论文")],
        },
        Term {
            id: "t-13".into(),
            industry_id: "ai".into(),
            category_id: "llm".into(),
            subcategory_id: None,
            title: "RLHF".into(),
            description: "人类反馈强化学习，通过人工标注偏好训练奖励模型，再用 PPO 等算法微调 LLM。".into(),
            websites: vec![web("https://arxiv.org/abs/2203.02155", "InstructGPT 论文")],
        },
        // AI · 机器学习
        Term {
            id: "t-14".into(),
            industry_id: "ai".into(),
            category_id: "ml".into(),
            subcategory_id: None,
            title: "过拟合".into(),
            description: "模型在训练集上表现良好但泛化能力差，通常因为模型复杂度过高或数据量不足。".into(),
            websites: vec![web("https://scikit-learn.org/stable/modules/learning_curve.html", "scikit-learn")],
        },
        Term {
            id: "t-15".into(),
            industry_id: "ai".into(),
            category_id: "ml".into(),
            subcategory_id: None,
            title: "梯度消失".into(),
            description: "深层网络反向传播时梯度趋近于零，导致前层参数无法有效更新的问题。".into(),
            websites: vec![web("https://arxiv.org/abs/1211.5063", "相关论文")],
        },
        // 医疗 · 诊断
        Term {
            id: "t-16".into(),
            industry_id: "medicine".into(),
            category_id: "diagnosis".into(),
            subcategory_id: None,
            title: "阳性预测值".into(),
            description: "PPV：检测阳性的患者中真正患病的比例，受患病率影响，与灵敏度、特异度共同评估诊断效能。".into(),
            websites: vec![web("https://www.ncbi.nlm.nih.gov/books/NBK556012/", "NCBI")],
        },
        Term {
            id: "t-17".into(),
            industry_id: "medicine".into(),
            category_id: "diagnosis".into(),
            subcategory_id: None,
            title: "受试者工作特征曲线".into(),
            description: "ROC Curve：以假阳率为横轴、真阳率为纵轴绘制的曲线，AUC 越接近 1 诊断能力越强。".into(),
            websites: vec![web("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2935927/", "NCBI")],
        },
        // 医疗 · 药理
        Term {
            id: "t-18".into(),
            industry_id: "medicine".into(),
            category_id: "pharmacology".into(),
            subcategory_id: None,
            title: "半衰期".into(),
            description: "药物血浆浓度降低至初始值一半所需时间，是设计给药间隔的关键参数。".into(),
            websites: vec![web("https://www.ncbi.nlm.nih.gov/books/NBK557498/", "NCBI")],
        },
        // 物理 · 量子力学
        Term {
            id: "t-19".into(),
            industry_id: "physics".into(),
            category_id: "quantum".into(),
            subcategory_id: None,
            title: "量子纠缠".into(),
            description: "两个粒子无论相距多远，测量其中一个的状态会瞬间影响另一个，无法用经典物理解释。".into(),
            websites: vec![web("https://arxiv.org/abs/quant-ph/0002037", "综述论文")],
        },
        Term {
            id: "t-20".into(),
            industry_id: "physics".into(),
            category_id: "quantum".into(),
            subcategory_id: None,
            title: "波函数坍缩".into(),
            description: "量子系统在测量前处于叠加态，观测后波函数立即坍缩为某一本征态的现象。".into(),
            websites: vec![web("https://plato.stanford.edu/entries/qt-measurement/", "Stanford Encyclopedia")],
        },
        // 机械 · 运动学
        Term {
            id: "t-21".into(),
            industry_id: "mechanics".into(),
            category_id: "kinematics".into(),
            subcategory_id: None,
            title: "自由度".into(),
            description: "机构中各构件相对于固定参考系独立运动的数目，是机构分析的基本参数。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Degrees_of_freedom_(mechanics)", "Wikipedia")],
        },
        // 金融 · 衍生品
        Term {
            id: "t-22".into(),
            industry_id: "finance".into(),
            category_id: "derivatives".into(),
            subcategory_id: None,
            title: "隐含波动率".into(),
            description: "将期权市场价格代入 Black-Scholes 模型反推出的波动率，反映市场对未来波动的预期。".into(),
            websites: vec![web("https://www.investopedia.com/terms/i/iv.asp", "Investopedia")],
        },
        Term {
            id: "t-23".into(),
            industry_id: "finance".into(),
            category_id: "derivatives".into(),
            subcategory_id: None,
            title: "Delta 对冲".into(),
            description: "通过持有与期权 Delta 值等量的标的资产，使整体组合对标的价格变动保持中性。".into(),
            websites: vec![web("https://www.investopedia.com/terms/d/deltahedging.asp", "Investopedia")],
        },
        // 法律 · 知识产权
        Term {
            id: "t-24".into(),
            industry_id: "law".into(),
            category_id: "ip".into(),
            subcategory_id: None,
            title: "合理使用".into(),
            description: "在满足特定条件（教育、评论、新闻报道等）下，可不经版权人许可使用受保护作品的例外原则。".into(),
            websites: vec![web("https://www.copyright.gov/fair-use/", "US Copyright Office")],
        },
        // 统计学 · 贝叶斯统计
        Term {
            id: "t-25".into(),
            industry_id: "statistics".into(),
            category_id: "bayesian".into(),
            subcategory_id: None,
            title: "先验概率".into(),
            description: "在观测到数据之前，基于已有知识或主观判断给定参数的概率分布。".into(),
            websites: vec![web("https://en.wikipedia.org/wiki/Prior_probability", "Wikipedia")],
        },
    ]
}
