/** Account Manager view state / 页面状态订阅：集中选择 controller 所需的 Zustand 字段。 */
import { useShallow } from "zustand/react/shallow"
import { useAccountManagerStore } from "@/features/account-manager/store"

export function useAccountManagerViewState() {
  return useAccountManagerStore(
    useShallow((s) => ({
      stations: s.stations,
      accounts: s.accounts,
      loading: s.loading,
      reloading: s.reloading,
      loadError: s.loadError,
      capabilities: s.capabilities,
      selectedStationId: s.selectedStationId,
      selectedAccountId: s.selectedAccountId,
      openingAccountId: s.openingAccountId,
      importingData: s.importingData,
      exportingData: s.exportingData,
      reorderingStations: s.reorderingStations,
      reorderingAccounts: s.reorderingAccounts,
      isAddStationOpen: s.isAddStationOpen,
      isAddAccountOpen: s.isAddAccountOpen,
      isEditStationOpen: s.isEditStationOpen,
      editingStation: s.editingStation,
      isEditAccountOpen: s.isEditAccountOpen,
      editingAccount: s.editingAccount,
      isDeleteStationOpen: s.isDeleteStationOpen,
      deletingStation: s.deletingStation,
      isDeleteAccountOpen: s.isDeleteAccountOpen,
      deletingAccount: s.deletingAccount,
      isQuickLoginOpen: s.isQuickLoginOpen,
      isExternalAppsOpen: s.isExternalAppsOpen,
      externalAppsAccountId: s.externalAppsAccountId,
      isFingerprintConfirmOpen: s.isFingerprintConfirmOpen,
      fingerprintSummary: s.fingerprintSummary,
      fingerprintTarget: s.fingerprintTarget,
      isFingerprintDetailOpen: s.isFingerprintDetailOpen,
      fingerprintDetail: s.fingerprintDetail,
      regionErrors: s.regionErrors,
      setSelectedAccountId: s.setSelectedAccountId,
      setAddStationOpen: s.setAddStationOpen,
      setAddAccountOpen: s.setAddAccountOpen,
      setQuickLoginOpen: s.setQuickLoginOpen,
      setExternalAppsOpen: s.setExternalAppsOpen,
      setFingerprintConfirmOpen: s.setFingerprintConfirmOpen,
      setFingerprintDetailOpen: s.setFingerprintDetailOpen,
      setEditStationOpen: s.setEditStationOpen,
      setEditingStation: s.setEditingStation,
      setEditAccountOpen: s.setEditAccountOpen,
      setEditingAccount: s.setEditingAccount,
      setDeleteStationOpen: s.setDeleteStationOpen,
      setDeletingStation: s.setDeletingStation,
      setDeleteAccountOpen: s.setDeleteAccountOpen,
      setDeletingAccount: s.setDeletingAccount,
    })),
  )
}
