#[macro_export]
macro_rules! app_invoke_handler {
    () => {
        tauri::generate_handler![
            // sleep inhibitor
            $crate::sleep_inhibitor::commands::toggle_sleep_inhibitor,
            $crate::sleep_inhibitor::commands::get_sleep_inhibitor_state,
            // system settings - finder
            $crate::system_settings::finder::set_finder_show_hidden_files,
            $crate::system_settings::finder::set_finder_show_pathbar,
            $crate::system_settings::finder::set_finder_show_statusbar,
            $crate::system_settings::finder::set_finder_show_library_dir,
            $crate::system_settings::finder::set_finder_show_file_extensions,
            $crate::system_settings::finder::set_finder_no_ds_store,
            // system settings - dock
            $crate::system_settings::dock::get_dock_orientation,
            $crate::system_settings::dock::set_dock_orientation,
            $crate::system_settings::dock::get_minimize_scale_enabled,
            $crate::system_settings::dock::set_minimize_scale_enabled,
            // system settings - keyboard
            $crate::system_settings::keyboard::get_keyboard_fn_key_state,
            $crate::system_settings::keyboard::set_keyboard_fn_key_state,
            $crate::system_settings::keyboard::get_auto_correct_state,
            $crate::system_settings::keyboard::set_auto_correct_state,
            $crate::system_settings::keyboard::get_smart_quotes_state,
            $crate::system_settings::keyboard::set_smart_quotes_state,
            $crate::system_settings::keyboard::get_smart_dashes_state,
            $crate::system_settings::keyboard::set_smart_dashes_state,
            $crate::system_settings::keyboard::get_auto_capitalize_state,
            $crate::system_settings::keyboard::set_auto_capitalize_state,
            // system settings - display
            $crate::system_settings::display::get_display_battery_percent,
            $crate::system_settings::display::set_display_battery_percent,
            // system settings - network
            $crate::system_settings::network::set_network_firewall_state,
            $crate::system_settings::network::set_network_ssh_state,
            $crate::system_settings::network::set_network_screen_sharing_state,
            $crate::system_settings::network::set_network_airdrop_disabled,
            // system settings - screenshot
            $crate::system_settings::screenshot::set_screenshot_format,
            $crate::system_settings::screenshot::set_screenshot_disable_shadow,
            $crate::system_settings::screenshot::set_screenshot_show_thumbnail,
            $crate::system_settings::screenshot::set_screenshot_save_location,
            // system settings - privacy
            $crate::system_settings::privacy::reset_tcc_permission,
            // system settings - semantic pane registry
            $crate::system_settings::system_pane_registry::open_battery_settings,
            $crate::system_settings::system_pane_registry::open_control_center_settings,
            $crate::system_settings::system_pane_registry::open_desktop_settings,
            $crate::system_settings::system_pane_registry::open_keyboard_settings,
            $crate::system_settings::system_pane_registry::open_localization_settings,
            $crate::system_settings::system_pane_registry::open_lock_screen_settings,
            $crate::system_settings::system_pane_registry::open_login_items_settings,
            $crate::system_settings::system_pane_registry::open_network_settings,
            $crate::system_settings::system_pane_registry::open_privacy_security_settings,
            // system settings - quick actions
            $crate::system_settings::quick_actions::lock_screen,
            $crate::system_settings::quick_actions::empty_trash,
            $crate::system_settings::quick_actions::sleep_now,
            $crate::system_settings::quick_actions::reboot_now,
            $crate::system_settings::quick_actions::shutdown_now,
            $crate::system_settings::quick_actions::get_lock_screen_password_enabled,
            $crate::system_settings::quick_actions::set_lock_screen_password_enabled,
            $crate::system_settings::quick_actions::get_lock_screen_password_delay,
            $crate::system_settings::quick_actions::set_lock_screen_password_delay,
            // system settings - system toggles
            $crate::system_settings::system_toggles::set_autohide_dock_state,
            $crate::system_settings::system_toggles::set_autohide_menu_bar_state,
            $crate::system_settings::system_toggles::set_dock_show_recents_state,
            $crate::system_settings::system_toggles::set_hide_desktop_icons_state,
            $crate::system_settings::system_toggles::set_low_power_mode_state,
            $crate::system_settings::system_toggles::set_screen_saver_state,
            // system settings - browser
            $crate::system_settings::browser::get_default_browser,
            $crate::system_settings::browser::set_default_browser,
            // system settings - login items
            $crate::system_settings::login_items::get_login_items,
            $crate::system_settings::login_items::remove_login_item,
            $crate::system_settings::login_items::get_launch_agents,
            $crate::system_settings::login_items::get_launch_daemons,
            $crate::system_settings::login_items::get_autostart_status,
            $crate::system_settings::login_items::set_autostart,
            // system settings - dev tools
            $crate::system_settings::dev_tools::json_format,
            $crate::system_settings::dev_tools::base64_encode,
            $crate::system_settings::dev_tools::base64_decode,
            $crate::system_settings::dev_tools::generate_uuid,
            $crate::system_settings::dev_tools::calculate_hash,
            $crate::system_settings::dev_tools::timestamp_convert,
            // system settings - network diagnostics
            $crate::system_settings::network::ping_host,
            $crate::system_settings::network::port_check,
            $crate::system_settings::network::get_local_ip,
            $crate::system_settings::network::get_wifi_info,
            $crate::app_updater::commands::check_for_app_update,
            $crate::app_updater::commands::download_and_install_app_update,
            $crate::app_updater::commands::cancel_app_update_download,
            $crate::app_updater::commands::restart_after_update,
            $crate::app_updater::commands::get_current_app_version,
            $crate::bootstrap::mark_main_ready,
            $crate::bootstrap::is_main_ready,
            $crate::bootstrap::list_startup_issues,
            $crate::app_manager::commands::scan_installed_apps,
            $crate::app_manager::commands::get_app_icon_base64,
            $crate::app_manager::commands::launch_app,
            $crate::app_manager::commands::reveal_app_in_finder,
            $crate::app_manager::commands::check_managed_app_updates,
            $crate::app_manager::commands::upgrade_app,
            $crate::app_manager::commands::uninstall_app,
            $crate::app_manager::commands::batch_upgrade_apps,
            $crate::app_manager::commands::batch_uninstall_apps,
            $crate::app_manager::commands::install_app,
            $crate::app_manager::commands::cancel_batch_operation,
            $crate::app_manager::commands::check_all_app_updates,
            $crate::app_manager::commands::open_in_mac_app_store,
            $crate::app_manager::commands::open_in_mac_app_store_updates,
            $crate::app_manager::commands::install_app_update,
            $crate::app_manager::commands::cancel_app_update,
            $crate::app_manager::commands::confirm_developer_id_change,
            $crate::system_settings::system_info::get_system_info,
            $crate::port_manager::commands::query_port_processes,
            $crate::port_manager::commands::kill_processes,
            $crate::dev_cleaner::commands::scan_dev_projects,
            $crate::dev_cleaner::commands::cleanup_projects,
            $crate::dev_cleaner::commands::stop_scan,
            $crate::dev_cleaner::custom_cleanup::get_custom_cleanup_commands,
            $crate::dev_cleaner::custom_cleanup::execute_custom_cleanup,
            $crate::dev_cleaner::custom_cleanup::stop_custom_cleanup,
            $crate::env_detector::commands::detect_env_tools,
            $crate::window_theme::commands::set_window_theme,
            $crate::account_manager::commands::list_stations,
            $crate::account_manager::commands::create_station,
            $crate::account_manager::commands::update_station,
            $crate::account_manager::commands::delete_station,
            $crate::account_manager::commands::list_all_accounts,
            $crate::account_manager::commands::create_account,
            $crate::account_manager::commands::update_account,
            $crate::account_manager::commands::delete_account,
            $crate::account_manager::commands::reveal_password,
            $crate::account_manager::commands::set_password,
            $crate::account_manager::commands::copy_password_to_clipboard,
            $crate::account_manager::commands::open_login_window,
            $crate::account_manager::commands::refresh_account,
            $crate::account_manager::commands::refresh_station,
            $crate::account_manager::commands::refresh_all,
            $crate::account_manager::commands::export_relay_data,
            $crate::account_manager::commands::import_relay_data,
            $crate::account_manager::commands::reorder_stations,
            $crate::account_manager::commands::reorder_accounts,
            $crate::account_manager::commands::detect_station_auth_profile,
            $crate::account_manager::commands::set_probe_strategy,
            $crate::account_manager::commands::reset_probe_strategy,
            $crate::account_manager::commands::create_ephemeral_account,
            $crate::account_manager::commands::set_session_ttl,
            $crate::account_manager::commands::set_station_network_proxy,
            $crate::account_manager::commands::set_account_proxy_enabled,
            $crate::account_manager::commands::proxy_login,
            $crate::account_manager::commands::handle_browser_open,
            $crate::account_manager::commands::proxy_login_new_account,
            $crate::account_manager::commands::list_external_apps,
            $crate::account_manager::commands::remove_external_app,
            $crate::account_manager::commands::list_external_app_bindings,
            $crate::token_calculator::commands::list_pricing_standards,
            $crate::token_calculator::commands::create_pricing_standard,
            $crate::token_calculator::commands::update_pricing_standard,
            $crate::token_calculator::commands::delete_pricing_standard,
            $crate::terminology::commands::list_terminology_data,
            $crate::terminology::commands::create_industry,
            $crate::terminology::commands::update_industry,
            $crate::terminology::commands::delete_industry,
            $crate::terminology::commands::create_category,
            $crate::terminology::commands::update_category,
            $crate::terminology::commands::delete_category,
            $crate::terminology::commands::create_subcategory,
            $crate::terminology::commands::update_subcategory,
            $crate::terminology::commands::delete_subcategory,
            $crate::terminology::commands::create_term,
            $crate::terminology::commands::update_term,
            $crate::terminology::commands::delete_term,
            $crate::terminology::commands::set_term_pinned,
            // file operations
            $crate::file_ops::write_text_file,
            // tray
            $crate::tray::set_tray_labels,
            // app preferences
            $crate::app_preferences::commands::get_close_behavior,
            $crate::app_preferences::commands::set_close_behavior,
            $crate::app_preferences::commands::quit_app,
            $crate::app_preferences::commands::hide_main_window,
        ]
    };
}
