/**
 * Repository / 仓储层: adapt Tauri account-manager commands; 只适配外部接口.
 */
import {
  browserSessionBrowsers,
  browserSessionCapture,
  browserSessionCaptureStation,
  browserSessionClearProfile,
  browserSessionClose,
  browserSessionCloseStation,
  browserSessionOpen,
  browserSessionOpenStation,
  browserSessionPreviewStation,
  browserSessionProbe,
  browserSessionStatus,
  browserSessionStatusStation,
  captureLoginFingerprint,
  confirmLoginFingerprint,
  copyPasswordToClipboard,
  createAccount,
  createEphemeralAccount,
  createStation,
  deleteAccount,
  deleteStation,
  detectStationAuthProfile,
  drainAuthProxyRequest,
  exportAccountSnapshot,
  exportRelayData,
  handleBrowserOpen,
  getAuthProxyInboxStatus,
  getAccountManagerCapabilities,
  getLoginFingerprintDetail,
  getLoginRulesOverview,
  importRelayData,
  listAccountLogs,
  listAllAccounts,
  listExternalAppBindings,
  listExternalApps,
  listStations,
  matchStationsByUrl,
  openLoginWindow,
  proxyLogin,
  proxyLoginNewAccount,
  refreshAccount,
  refreshAll,
  refreshStation,
  removeExternalApp,
  reorderAccounts,
  reorderStations,
  resetProbeStrategy,
  retryAccountManagerInit,
  revealPassword,
  setAccountProxyEnabled,
  setAccountRefreshSchedule,
  setPassword,
  setProbeStrategy,
  setSessionTtl,
  setStationNetworkProxy,
  updateAccount,
  updateLoginRules,
  updateStation,
} from "@/lib/tauri/commands/account-manager"
import { openExternal } from "@/platform/shell"
import { openPlatformDialog, savePlatformDialog } from "@/platform/dialog"
import {
  exportBrowserExtension,
  getBrowserExtensionStatus,
  openBrowserExtensionsPage,
} from "@/lib/tauri/commands/browser-ext"

export const accountManagerRepository = {
  getAccountManagerCapabilities,
  retryInit: retryAccountManagerInit,
  listStations,
  createStation,
  updateStation,
  deleteStation,
  listAllAccounts,
  createAccount,
  updateAccount,
  deleteAccount,
  revealPassword,
  setPassword,
  copyPasswordToClipboard,
  openLoginWindow,
  refreshAccount,
  refreshStation,
  refreshAll,
  exportRelayData,
  importRelayData,
  reorderStations,
  reorderAccounts,
  detectStationAuthProfile,
  setProbeStrategy,
  resetProbeStrategy,
  createEphemeralAccount,
  setSessionTtl,
  setStationNetworkProxy,
  setAccountProxyEnabled,
  setAccountRefreshSchedule,
  listAccountLogs,
  matchStationsByUrl,
  captureLoginFingerprint,
  confirmLoginFingerprint,
  getLoginFingerprintDetail,
  getLoginRulesOverview,
  updateLoginRules,
  exportAccountSnapshot,
  proxyLogin,
  handleBrowserOpen,
  getAuthProxyInboxStatus,
  drainAuthProxyRequest,
  proxyLoginNewAccount,
  listExternalApps,
  removeExternalApp,
  listExternalAppBindings,
  browserSessionBrowsers,
  browserSessionOpen,
  browserSessionStatus,
  browserSessionClose,
  browserSessionCapture,
  browserSessionProbe,
  browserSessionClearProfile,
  browserSessionOpenStation,
  browserSessionStatusStation,
  browserSessionCloseStation,
  browserSessionPreviewStation,
  browserSessionCaptureStation,
  // 互通 I3/I5：读写**日常浏览器**（扩展通道）所需的导出/状态命令。
  getBrowserExtensionStatus,
  exportBrowserExtension,
  openBrowserExtensionsPage,
  openExternal,
  openPlatformDialog,
  savePlatformDialog,
}

export type AccountManagerRepository = typeof accountManagerRepository
