/**
 * Repository / 仓储层: adapt Tauri account-manager commands; 只适配外部接口.
 */
import {
  copyPasswordToClipboard,
  createAccount,
  createEphemeralAccount,
  createStation,
  deleteAccount,
  deleteStation,
  detectStationAuthProfile,
  drainAuthProxyRequest,
  exportRelayData,
  handleBrowserOpen,
  getAuthProxyInboxStatus,
  importRelayData,
  listAllAccounts,
  listExternalAppBindings,
  listExternalApps,
  listStations,
  openLoginWindow,
  proxyLogin,
  proxyLoginNewAccount,
  refreshAccount,
  refreshAll,
  refreshStation,
  removeExternalApp,
  reorderAccounts,
  reorderStations,
  resetProbeStrategy,
  revealPassword,
  setAccountProxyEnabled,
  setPassword,
  setProbeStrategy,
  setSessionTtl,
  setStationNetworkProxy,
  updateAccount,
  updateStation,
} from "@/lib/tauri/commands/account-manager"
import { openExternal } from "@/platform/shell"
import { openPlatformDialog, savePlatformDialog } from "@/platform/dialog"

export const accountManagerRepository = {
  listStations,
  createStation,
  updateStation,
  deleteStation,
  listAllAccounts,
  createAccount,
  updateAccount,
  deleteAccount,
  revealPassword,
  setPassword,
  copyPasswordToClipboard,
  openLoginWindow,
  refreshAccount,
  refreshStation,
  refreshAll,
  exportRelayData,
  importRelayData,
  reorderStations,
  reorderAccounts,
  detectStationAuthProfile,
  setProbeStrategy,
  resetProbeStrategy,
  createEphemeralAccount,
  setSessionTtl,
  setStationNetworkProxy,
  setAccountProxyEnabled,
  proxyLogin,
  handleBrowserOpen,
  getAuthProxyInboxStatus,
  drainAuthProxyRequest,
  proxyLoginNewAccount,
  listExternalApps,
  removeExternalApp,
  listExternalAppBindings,
  openExternal,
  openPlatformDialog,
  savePlatformDialog,
}

export type AccountManagerRepository = typeof accountManagerRepository
